language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install
  - composer require openlss/lib-array2xml --dev
  - composer require symfony/yaml --dev

script: ./vendor/bin/phpunit  --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false